#------------------------------
# General Site Settings
title: Barrie Callender
tagline: My Jewish family history and other tales
email: barrie@callenb.org
description: A blog mostly about my Jewish family history starting from my Great Great Grandparents Jacob Solomons and Hannah Levinson. #>- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://callenb.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/barrie_callender_400x400.jpg

#------------------------------
# Author Settings
author:
  name: Barrie Callender
  image: '/images/barrie_callender_400x400.jpg'
  avatar: '/images/barrie_callender_400x400.jpg'
  description: 'My name is Barrie Callender. I am a freelancer working as a Project Management System Implementation Consultant'

twitter:
  username: callenb
  card: summary

social:
  name: Barrie Callender
  links:
    - https://twitter.com/callenb
    - https://www.facebook.com/barrie.callender
    - https://www.linkedin.com/in/barriecallender
    - https://github.com/callenb
    - https://github.com/usingprimavera

#------------------------------
# Contact Links

# Example of adding a new link to the footer - { icon: 'ion-logo-github', link: 'https://github.com'}
# Other icons can be found at https://ionicons.com/v4/
contact:
- { name: 'Github', icon: 'ion-logo-github', link: 'https://github.com/callenb'}
- { name: 'Twitter', icon: 'ion-logo-twitter', link: 'https://twitter.com/callenb'}
- { name: 'LinkedIn', icon: 'ion-logo-linkedin', link: 'https://www.linkedin.com/in/barriecallender/'}

#------------------------------
# Comment Section (Disqus)
disqus-identifier: callenb

#-------------------------------
# Newsletter
tinyletter: true # To enable the TinyLetter form, use the value true. To turn off use the value false.
tinyletter-identifier: 'https://tinyletter.com/callenb' # Add your TinyLetter subscribe form.
tinyletter-title: 'Get Occasional Updates'
tinyletter-description: 'Subscribe to our newsletter to hear what''s swimming around in my head.'

#-------------------------------
# Google Analytics
# google-analytics: UA-26390665-1 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - octopress-image-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-last-modified-at
  - jekyll-hebcal

paginate: 9
paginate_path: "/page/:num"
permalink: pretty

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
      
include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
#-----------------------------


# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft



# exlude pdf files from sitemap
#
defaults:
  -
    scope:
      path: "images/**/*.pdf"
    values:
      sitemap: false
