#------------------------------
# General Site Settings
title: Barrie Callender
tagline: My Jewish family history and other tales
email: barrie@callenb.org
description: A blog mostly about my Jewish family history starting from my great great grandparents Jacob Solomons and Hannah Levinson. #>- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://callenb.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/barrie_callender_400x400.jpg

#------------------------------
# Author Settings
author:
  name: Barrie Callender
  image: '/images/barrie_callender_400x400.jpg'
  avatar: '/images/barrie_callender_400x400.jpg'
  description: 'My name is Barrie Callender. I am a freelancer working as a Project Management System Implementation Consultant'

twitter:
  username: callenb
  card: summary

social:
  name: Barrie Callender
  links:
    - https://twitter.com/callenb
    - https://www.facebook.com/barrie.callender
    - https://www.linkedin.com/in/barriecallender
    - https://github.com/callenb
    - https://github.com/usingprimavera

#------------------------------
# Contact Links

# Example of adding a new link to the footer - { icon: 'ion-logo-github', link: 'https://github.com'}
# Other icons can be found at https://ionicons.com/v4/
contact:
- { name: 'Github', icon: 'ion-logo-github', link: 'https://github.com/callenb'}
- { name: 'Twitter', icon: 'ion-logo-twitter', link: 'https://twitter.com/callenb'}
- { name: 'LinkedIn', icon: 'ion-logo-linkedin', link: 'https://www.linkedin.com/in/barriecallender/'}

#------------------------------
# Comment Section (Disqus)
disqus-identifier: callenb

#-------------------------------
# Newsletter
tinyletter: true # To enable the TinyLetter form, use the value true. To turn off use the value false.
tinyletter-identifier: 'https://tinyletter.com/callenb' # Add your TinyLetter subscribe form.
tinyletter-title: 'Get Occasional Updates'
tinyletter-description: 'Subscribe to our newsletter to hear what''s swimming around in my head.'

#-------------------------------
# Google Analytics
# google-analytics: UA-26390665-1 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - octopress-image-tag
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-last-modified-at
  - jekyll-hebcal

permalink: pretty

#jekyll-paginate-v2
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
      
include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
#-----------------------------


# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft



# exlude pdf files from sitemap
#
defaults:
  -
    scope:
      path: "images/**/*.pdf"
    values:
      sitemap: false
